return {
    -- MH_L_Elbow
    
    -- Ejemplos añadidos desde rms-nativeaccessories config.lua
    Accessories = {
        {
            hashid = "native_1",
            alwaysAttached = false,
            category = "native",
            model = "s_cranefeathertrinket01x",
            bone = "HairScale_B", 
            offset = { x = -0.06, y = 0.03, z = 0.10, pitch = 18.0, roll = 3.0, yaw = 84.0 },
        },
        {
            hashid = "native_2",
            alwaysAttached = false,
            category = "native",
            model = "p_arrowbundle02x",
            bone = "CP_L_WaistOuter",
            offset = { x = -0.07, y = -0.05, z = 0.08, pitch = -8.0, roll = 0.0, yaw = 149.0 },
        },
        {
            hashid = "native_3",
            alwaysAttached = false,
            category = "native",
            model = "s_cateyetrinket01x_1",
            bone = "HairScale_B",
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 94.0 },
        },
        {
            hashid = "native_4",
            alwaysAttached = false,
            category = "native",
            model = "s_crowbeaktrinket01x_1",
            bone = "HairScale_B",
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 94.0 },
        },{
            hashid = "native_5",
            alwaysAttached = false,
            category = "native",
            model = "s_ornategoldtrinket01x",
            bone = "SKEL_SPINED",
            offset = { x = -0.06, y = 0.03, z = 0.06, pitch = 18.0, roll = 3.0, yaw = 94.0 },
        },
        {
            hashid = "native_6",
            alwaysAttached = false,
            category = "native",
            model = 's_squirreltoothtrinket01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "native_7",
            alwaysAttached = false,
            category = "native",
            model = 's_squirreltoothtrinket01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "native_8",
            alwaysAttached = false,
            category = "native",
            model = 's_asteroidchunktrinket',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "native_9",
            alwaysAttached = false,
            category = "native",
            model = 's_bullhorntrinket01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "native_10",
            alwaysAttached = false,
            category = "native",
            model = 's_futuristictrinket01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        
        {
            hashid = "native_11",
            alwaysAttached = false,
            category = "native",
            model = 's_hawktalontrinket01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "native_12",
            alwaysAttached = false,
            category = "native",
            model = 's_hawktalontrinket01x_1',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
       {
            hashid = "native_13",
            alwaysAttached = false,
            category = "native",
            model = 's_gilamonstertrinket', -- 'p_blowgundart01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = -0.05,
                y = 0.08,
                z = -0.04,
                pitch = -65.0,
                roll = 5.0,
                yaw = 0.0,
            },
        },
    },

    Cosmetics = {
        --[[ {
            hashid = "toys_1",
            alwaysAttached = false,
            category = "toys",
            model = 'p_bathbrush01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.05,
                y = 0.12,
                z = 0.08,
                pitch = -30.0,
                roll = 15.0,
                yaw = 150.0,
            },
        }, ]]
        --[[]]
        {
            hashid = "toys_1",
            alwaysAttached = false,
            category = "toys",
            model = 'mp005_example_thickness',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        
        {
            hashid = "toys_2",
            alwaysAttached = false,
            category = "toys",
            model = 'mp005_s_hl_cmb_ivry',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_3",
            alwaysAttached = false,
            category = "toys",
            model = 'mp005_s_hl_hp_crvdwd',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        
        {
            hashid = "toys_4",
            alwaysAttached = false,
            category = "toys",
            model = 'mp005_s_hl_hp_jde',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_5",
            alwaysAttached = false,
            category = "toys",
            model = 'p_keys01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = 0.05,
                z = 0.11,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
    },
    Bags = {
        {
            hashid = "bags_1",
            alwaysAttached = false,
            category = "bags",
            model = 'p_bag_voodoo01x',
            bone = 'SKEL_R_FOREARM',
            offset = {
                x = 0.05,
                y = -0.05,
                z = -0.05,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "bags_2",
            alwaysAttached = false,
            category = "bags",
            model = 's_squirrelmarston01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = -0.03,
                z = 0.08,
                pitch = 10.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "bags_3",
            alwaysAttached = false,
            category = "bags",
            model = 'p_cs_saddle_bag01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = -0.03,
                z = 0.08,
                pitch = 10.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "bags_4",
            alwaysAttached = false,
            category = "bags",
            model = 's_mp_moneybag01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.00,
                y = -0.03,
                z = 0.08,
                pitch = 10.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "bags_5",
            alwaysAttached = false,
            category = "bags",
            model = 'mp009_s_mp_pickup_jewelrybag01x',
            bone = 'SKEL_SPINED',
            offset = {
                x = 0.14,
                y = 0.14,
                z = 0.04,
                pitch = -2.0,
                roll = -8.0,
                yaw = -44.0,
            },
        },
    },
    Neck = {

        {
            hashid = "neck_5",
            alwaysAttached = false,
            category = "neck",
            model = 's_re_relicguama02x',
            bone = 'SKEL_NECK0',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_6",
            alwaysAttached = false,
            category = "neck",
            model = 's_re_goldrelicguama01x',
            bone = 'SKEL_NECK1',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_7",
            alwaysAttached = false,
            category = "neck",
            model = 'p_ancientfertilityfgr01x',
            bone = 'SKEL_NECK2',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_8",
            alwaysAttached = false,
            category = "neck",
            model = 's_urndiscoverable01x',
            bone = 'SKEL_NECK2',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_10",
            alwaysAttached = false,
            category = "neck",
            model = 'p_cs_noose01xb',
            bone = 'SKEL_NECK2',
            offset = {
                x = 0.00,
                y = -0.15,
                z = 0.15,
                pitch = -45.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
    },
    Medal = {

        {
            hashid = "medal_1",
            alwaysAttached = false,
            category = "medal",
            model = 'p_eaglependant01x',
            bone = 'SKEL_NECK0',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 94.0 },
        },

        {
            hashid = "medal_2",
            alwaysAttached = false,
            category = "medal",
            model = 'p_deputybadge01x',
            bone = 'SKEL_NECK1',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
        {
            hashid = "medal_3",
            alwaysAttached = false,
            category = "medal",
            model = 's_pantherclawtrinket01x',
            bone = 'SKEL_NECK2',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
        {
            hashid = "medal_4",
            alwaysAttached = false,
            category = "medal",
            model = 's_coachlock02x',
            bone = 'SKEL_L_FOREARM',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
        {
            hashid = "medal_5",
            alwaysAttached = false,
            category = "medal",
            model = 's_wagonprison_lock',
            bone = 'SKEL_R_FOREARM',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
        {
            hashid = "medal_6",
            alwaysAttached = false,
            category = "medal",
            model = 's_wagonprison_lock',
            bone = 'SKEL_L_UPPERARM',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
        {
            hashid = "medal_7",
            alwaysAttached = false,
            category = "medal",
            model = 'p_ancientmayanhead01x',
            bone = 'SKEL_L_HAND',
            offset = { x = -0.06, y = 0.03, z = 0.08, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
        {
            hashid = "medal_8",
            alwaysAttached = false,
            category = "medal",
            model = 'p_cs_warmedal01x',
            bone = 'SKEL_R_HAND',
            offset = { x = -0.06, y = 0.03, z = 0.03, pitch = 18.0, roll = 3.0, yaw = 274.0 },
        },
    },
    Masks = {
        {
            hashid = "mask_1",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull06x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.00,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_2",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull01x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_3",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull02x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_4",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull03x',
            bone = 'PH_HeadProp', --  'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_5",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull04x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_6",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull05x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_8",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull07x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_9",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull08x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0, -- 0.08,
                y = 0.23, -- -0.04,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "mask_10",
            alwaysAttached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull09x',
            bone = 'PH_HeadProp', -- 'PH_HeadProp',
            offset = {
                x = 0.0,
                y = 0.23,
                z = 0.10,
                pitch = -15.0,
                roll = 0.0,
                yaw = 180.0,
            },
        },

    },
}

